services:
  postgres:
    image: 'postgres:13'
    ports:
      - ${DB_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    env_file:
      - .env

  shortener:
    image: ghcr.io/jakub3628800/shortener:latest
    ports:
      - ${APP_PORT:-8000}:8000
    environment:
      DB_HOST: postgres
    env_file:
      - .env
    depends_on:
      - postgres
