services:
  postgres:
    image: 'postgres:13'
    network_mode: host
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    env_file:
      - .env

  shortener:
    image: ghcr.io/jakub3628800/shortener:latest
    network_mode: host
    environment:
      DB_HOST: localhost
    env_file:
      - .env
    depends_on:
      - postgres
