version: "3.8"
services:
  postgres:
    image: 'postgres:13'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: urldatabase

  shortener:
    image: ghcr.io/jakub3628800/shortener:latest
    ports:
      - 8000:8000
    environment:
      DB_PORT: 5432
      DB_HOST: postgres
      DB_NAME: urldatabase
      DB_USER: localuser
      DB_PASS: password123
