version: "3.4"
services:
  postgres:
    image: 'postgres:13'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: urldatabase