"""add url table

Revision ID: d6f2bb97ceff
Revises: 5da9b1a53149
Create Date: 2025-03-01 16:44:15.188979

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic.operations import Operations as op  # type: ignore



# revision identifiers, used by Alembic.
revision: str = 'd6f2bb97ceff'
down_revision: Union[str, None] = '5da9b1a53149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'short_urls',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url_key', sa.String(), nullable=False),
        sa.Column('target', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('short_urls')
    # ### end Alembic commands ###
