name: Deploy Docker

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: shortener

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag "$IMAGE_NAME" --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo "$IMAGE_ID" | tr '[:upper:]' '[:lower:]')
          # Strip git ref prefix from version
          VERSION="${{ github.ref }}"
          VERSION="${VERSION##*/}"
          # Strip "v" prefix from tag name
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION="${VERSION#v}"
          fi
          # Use Docker `latest` tag convention
          if [ "$VERSION" = "master" ]; then
            VERSION=latest
          fi
          echo "IMAGE_ID=$IMAGE_ID"
          echo "VERSION=$VERSION"
          docker tag "$IMAGE_NAME" "$IMAGE_ID:$VERSION"
          docker push "$IMAGE_ID:$VERSION"
