on:
  release:
    types: [published, created, edited]

name: Deploy to Azure workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        environment:
          name: production
          url: ${{ steps.create_release.outputs.html_url }}
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            image: ${{ secrets.DOCKER_IMAGE }}
            name: shortener
            dns-name-label: shortener
            location: 'westeurope'
            memory: 0.5
            environment-variables: APPLICATION_PORT=80 DB_NAME=shortenerdb DB_PORT=5432 DB_USER=shortenerdb@shortenerdb
            secure-environment-variables: DB_HOST=${{ secrets.DB_HOST }} DB_PASS=${{ secrets.DB_PASS }}
