name: Merge Bot

on:
  pull_request:
    types:
      - ready_for_review

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
    - name: Tests done check
      uses: squalrus/merge-bot@v0.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        test: true
        method: rebase
        delete_source_branch: true
