# This workflow runs pytest on the service code
name: Pytest Pull Request workflow

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master, test-gh-action ]

#set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: async-url-shortener
  IMAGE_NAME: shortener

jobs:

  pytest_with_coverage:
    # Run pytest, upload coverage to a githubs gist so that badge can display it

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: urldatabase

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.14
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'
    - name: Install uv
      uses: astral-sh/setup-uv@v7
    - name: Install dependencies
      run: uv sync --all-extras

    - name: Test with pytest
      run: uv run pytest --cov=shortener
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: urldatabase
        DB_USER: postgres
        DB_PASSWORD: pass
